// <auto-generated />
using System;
using HrManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrManagementDbContext))]
    [Migration("20260902034515_AddPayrollEmployeeSnapshots")]
    partial class AddPayrollEmployeeSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("HrManagement.Domain.Attendance.Calendars.HolidayCalendarDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("UX_HolidayCalendarDays_Date");

                    b.HasIndex("IsActive");

                    b.ToTable("HolidayCalendarDays", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Corrections.AttendanceCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AffectedEventId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AfterEventType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AfterOccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AttendanceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BeforeEventType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BeforeOccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CorrectedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceRecordId", "Revision")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceCorrections_Record_Revision");

                    b.HasIndex("EmployeeId", "CorrectedAtUtc")
                        .HasDatabaseName("IX_AttendanceCorrections_Employee_CorrectedAtUtc");

                    b.HasIndex("AttendanceRecordId", "AffectedEventId", "Revision")
                        .HasDatabaseName("IX_AttendanceCorrections_Record_Event_Revision");

                    b.ToTable("AttendanceCorrections", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Records.AttendanceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttendanceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceRecordId")
                        .HasDatabaseName("IX_AttendanceEvents_AttendanceRecordId");

                    b.HasIndex("AttendanceRecordId", "OccurredAtUtc")
                        .HasDatabaseName("IX_AttendanceEvents_Record_OccurredAtUtc");

                    b.HasIndex("EmployeeId", "OccurredAtUtc")
                        .HasDatabaseName("IX_AttendanceEvents_Employee_OccurredAtUtc");

                    b.ToTable("AttendanceEvents", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Records.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("EarlyLeaveMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmploymentPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectationSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ExpectationSourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectationSourceName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedBreakMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("ExpectedEndTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("ExpectedStartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LateMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkScheduleAssignmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkedMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EmploymentPeriodId")
                        .HasDatabaseName("IX_AttendanceRecords_EmploymentPeriodId");

                    b.HasIndex("WorkDate")
                        .HasDatabaseName("IX_AttendanceRecords_WorkDate");

                    b.HasIndex("WorkScheduleAssignmentId")
                        .HasDatabaseName("IX_AttendanceRecords_WorkScheduleAssignmentId");

                    b.HasIndex("WorkScheduleId")
                        .HasDatabaseName("IX_AttendanceRecords_WorkScheduleId");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .IsUnique()
                        .HasDatabaseName("UX_AttendanceRecords_Employee_WorkDate");

                    b.ToTable("AttendanceRecords", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Schedules.EmployeeWorkScheduleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmploymentPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeWorkScheduleAssignments_EmployeeId_Open")
                        .HasFilter("\"EffectiveTo\" IS NULL");

                    b.HasIndex("EmploymentPeriodId")
                        .HasDatabaseName("IX_EmployeeWorkScheduleAssignments_EmploymentPeriodId");

                    b.HasIndex("WorkScheduleId")
                        .HasDatabaseName("IX_EmployeeWorkScheduleAssignments_WorkScheduleId");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .HasDatabaseName("IX_EmployeeWorkScheduleAssignments_Employee_EffectiveFrom");

                    b.ToTable("EmployeeWorkScheduleAssignments", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Schedules.WorkSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkSchedules_Code");

                    b.HasIndex("IsActive");

                    b.ToTable("WorkSchedules", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Schedules.WorkScheduleDateOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkDate")
                        .HasDatabaseName("IX_WorkScheduleDateOverrides_WorkDate");

                    b.HasIndex("WorkScheduleId", "WorkDate")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkScheduleDateOverrides_Schedule_Date");

                    b.ToTable("WorkScheduleDateOverrides", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Schedules.WorkScheduleDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BreakMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkScheduleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkScheduleId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("UX_WorkScheduleDays_Schedule_DayOfWeek");

                    b.ToTable("WorkScheduleDays", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Timesheets.MonthlyTimesheetDaySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttendanceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectionRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("EarlyLeaveMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedPlannedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TimesheetPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkedMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceRecordId");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .HasDatabaseName("IX_MonthlyTimesheetSnapshots_Employee_Date");

                    b.HasIndex("TimesheetPeriodId", "EmployeeId", "WorkDate")
                        .IsUnique()
                        .HasDatabaseName("UX_MonthlyTimesheetSnapshots_Period_Employee_Date");

                    b.ToTable("MonthlyTimesheetDaySnapshots", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Timesheets.TimesheetPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClosedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedByUsername")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("UX_TimesheetPeriods_Year_Month");

                    b.ToTable("TimesheetPeriods", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EmployeeId", "OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.EmploymentPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_EmploymentPeriods_EmployeeId_Open")
                        .HasFilter("\"EndDate\" IS NULL");

                    b.HasIndex("EmployeeId", "StartDate");

                    b.ToTable("EmploymentPeriods", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.OrganizationAssignments.EmployeeOrganizationAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmploymentPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_EmployeeOrganizationAssignments_DepartmentId");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeOrganizationAssignments_EmployeeId_Open")
                        .HasFilter("\"EndDate\" IS NULL");

                    b.HasIndex("EmploymentPeriodId")
                        .HasDatabaseName("IX_EmployeeOrganizationAssignments_EmploymentPeriodId");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("IX_EmployeeOrganizationAssignments_PositionId");

                    b.HasIndex("EmployeeId", "StartDate");

                    b.ToTable("EmployeeOrganizationAssignments", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Profiles.EmployeeAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ward")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Type")
                        .IsUnique();

                    b.ToTable("EmployeeAddresses", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Profiles.EmployeeEmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeEmergencyContacts_EmployeeId_Primary")
                        .HasFilter("\"IsPrimary\" = 1");

                    b.HasIndex("EmployeeId", "Id")
                        .HasDatabaseName("IX_EmployeeEmergencyContacts_EmployeeId_Id");

                    b.ToTable("EmployeeEmergencyContacts", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Profiles.EmployeeIdentificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingCountry")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfIssue")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Type")
                        .HasDatabaseName("IX_EmployeeIdentificationRecords_EmployeeId_Type");

                    b.ToTable("EmployeeIdentificationRecords", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Profiles.EmployeePersonalProfile", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeePersonalProfiles", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Leave.Requests.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmploymentPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubmittedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentPeriodId")
                        .HasDatabaseName("IX_LeaveRequests_EmploymentPeriodId");

                    b.HasIndex("LeaveTypeId")
                        .HasDatabaseName("IX_LeaveRequests_LeaveTypeId");

                    b.HasIndex("Status", "SubmittedAtUtc")
                        .HasDatabaseName("IX_LeaveRequests_Status_SubmittedAtUtc");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate")
                        .HasDatabaseName("IX_LeaveRequests_Employee_DateRange");

                    b.ToTable("LeaveRequests", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Leave.Requests.LeaveRequestStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChangedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedByUsername")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LeaveRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeaveRequestId", "ChangedAtUtc")
                        .HasDatabaseName("IX_LeaveRequestStatusChanges_Request_ChangedAtUtc");

                    b.ToTable("LeaveRequestStatusChanges", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Leave.Types.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_LeaveTypes_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_LeaveTypes_IsActive");

                    b.ToTable("LeaveTypes", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Organization.Departments.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Departments_Code");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Organization.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Positions_Code");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Overtime.Requests.OvertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmploymentPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubmittedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentPeriodId")
                        .HasDatabaseName("IX_OvertimeRequests_EmploymentPeriodId");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .IsUnique()
                        .HasDatabaseName("UX_OvertimeRequests_Employee_WorkDate_Active")
                        .HasFilter("\"Status\" IN (1, 2)");

                    b.HasIndex("Status", "WorkDate")
                        .HasDatabaseName("IX_OvertimeRequests_Status_WorkDate");

                    b.ToTable("OvertimeRequests", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Overtime.Requests.OvertimeRequestStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApprovedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChangedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedByUsername")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OvertimeRequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OvertimeRequestId", "ChangedAtUtc")
                        .HasDatabaseName("IX_OvertimeRequestStatusChanges_Request_ChangedAtUtc");

                    b.ToTable("OvertimeRequestStatusChanges", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Payroll.Compensation.EmployeeCompensation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmploymentPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyBaseSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentPeriodId")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeCompensations_EmploymentPeriod_Open")
                        .HasFilter("\"EffectiveTo\" IS NULL");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .HasDatabaseName("IX_EmployeeCompensations_Employee_EffectiveFrom");

                    b.HasIndex("EmploymentPeriodId", "EffectiveFrom")
                        .IsUnique()
                        .HasDatabaseName("UX_EmployeeCompensations_EmploymentPeriod_EffectiveFrom");

                    b.ToTable("EmployeeCompensations", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Payroll.Periods.PayrollPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClosedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClosedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedByUsername")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TimesheetPeriodId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetPeriodId")
                        .IsUnique()
                        .HasDatabaseName("UX_PayrollPeriods_TimesheetPeriodId");

                    b.HasIndex("Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("UX_PayrollPeriods_Year_Month");

                    b.ToTable("PayrollPeriods", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Payroll.Snapshots.PayrollEmployeeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApprovedOvertimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseSalaryAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PayableOvertimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PayrollPeriodId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_PayrollEmployeeSnapshots_Employee");

                    b.HasIndex("PayrollPeriodId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_PayrollEmployeeSnapshots_Period_Employee");

                    b.ToTable("PayrollEmployeeSnapshots", (string)null);
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Corrections.AttendanceCorrection", b =>
                {
                    b.HasOne("HrManagement.Domain.Attendance.Records.AttendanceRecord", null)
                        .WithMany()
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Records.AttendanceEvent", b =>
                {
                    b.HasOne("HrManagement.Domain.Attendance.Records.AttendanceRecord", null)
                        .WithMany()
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Records.AttendanceRecord", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.EmploymentPeriod", null)
                        .WithMany()
                        .HasForeignKey("EmploymentPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Attendance.Schedules.EmployeeWorkScheduleAssignment", null)
                        .WithMany()
                        .HasForeignKey("WorkScheduleAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Attendance.Schedules.WorkSchedule", null)
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Schedules.EmployeeWorkScheduleAssignment", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.EmploymentPeriod", null)
                        .WithMany()
                        .HasForeignKey("EmploymentPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Attendance.Schedules.WorkSchedule", null)
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Schedules.WorkScheduleDateOverride", b =>
                {
                    b.HasOne("HrManagement.Domain.Attendance.Schedules.WorkSchedule", null)
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Schedules.WorkScheduleDay", b =>
                {
                    b.HasOne("HrManagement.Domain.Attendance.Schedules.WorkSchedule", null)
                        .WithMany()
                        .HasForeignKey("WorkScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Attendance.Timesheets.MonthlyTimesheetDaySnapshot", b =>
                {
                    b.HasOne("HrManagement.Domain.Attendance.Records.AttendanceRecord", null)
                        .WithMany()
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Attendance.Timesheets.TimesheetPeriod", null)
                        .WithMany()
                        .HasForeignKey("TimesheetPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Employee", b =>
                {
                    b.HasOne("HrManagement.Domain.Organization.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HrManagement.Domain.Organization.Positions.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.EmploymentPeriod", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.OrganizationAssignments.EmployeeOrganizationAssignment", b =>
                {
                    b.HasOne("HrManagement.Domain.Organization.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.EmploymentPeriod", null)
                        .WithMany()
                        .HasForeignKey("EmploymentPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Organization.Positions.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Profiles.EmployeeAddress", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Profiles.EmployeeEmergencyContact", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Profiles.EmployeeIdentificationRecord", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Employees.Profiles.EmployeePersonalProfile", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithOne()
                        .HasForeignKey("HrManagement.Domain.Employees.Profiles.EmployeePersonalProfile", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Leave.Requests.LeaveRequest", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.EmploymentPeriod", null)
                        .WithMany()
                        .HasForeignKey("EmploymentPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Leave.Types.LeaveType", null)
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Leave.Requests.LeaveRequestStatusChange", b =>
                {
                    b.HasOne("HrManagement.Domain.Leave.Requests.LeaveRequest", null)
                        .WithMany()
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Overtime.Requests.OvertimeRequest", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.EmploymentPeriod", null)
                        .WithMany()
                        .HasForeignKey("EmploymentPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Overtime.Requests.OvertimeRequestStatusChange", b =>
                {
                    b.HasOne("HrManagement.Domain.Overtime.Requests.OvertimeRequest", null)
                        .WithMany()
                        .HasForeignKey("OvertimeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Payroll.Compensation.EmployeeCompensation", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Employees.EmploymentPeriod", null)
                        .WithMany()
                        .HasForeignKey("EmploymentPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Payroll.Periods.PayrollPeriod", b =>
                {
                    b.HasOne("HrManagement.Domain.Attendance.Timesheets.TimesheetPeriod", null)
                        .WithMany()
                        .HasForeignKey("TimesheetPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HrManagement.Domain.Payroll.Snapshots.PayrollEmployeeSnapshot", b =>
                {
                    b.HasOne("HrManagement.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HrManagement.Domain.Payroll.Periods.PayrollPeriod", null)
                        .WithMany()
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
